export const uiWords: Record<string, string> = {
    news: 'Новости',
    promo: 'Промо',
    promotions: 'Промоушены',
    wallet: 'Кошелек',
    activity: 'Активность',
    bonusActivity: 'Бонусная активность',
    notify: 'Уведомления',
    profile: 'Профиль',

    information: 'Информация',
    logout: 'Выйти',
    language: 'Язык',
    noNews: 'Нет новостей',
    noPromo: 'Нет доступных промо',
    all: 'Все',
    archived: 'Архив',
    archive: 'В архив',
    cancel: 'Отмена',
    unread: 'Непр.',
    noNotifications: 'Уведомлений нет',
    noArchiveNotifications: 'Архив пуст',
    confirmArchive: 'Переместить все уведомления в архив?',
    walletAvailableBalance: 'Сейчас доступно',
    thisMonth: 'Текущий месяц',
    nextMonth: 'Следующий месяц',
    inactiveBranches: 'Неактивные ветки',
    selfActivity: 'Личная',
    branchActivity: 'В ветках',

    yes: 'Да',
    yesRestrictions: 'Да, с ограничениями',
    no: 'Нет',
    branchWOActivity: 'Ветки без активности',

    sessionExpired: 'Сессия авторизации истекла',
    biometryReason: 'Вход в приложение',
    biometryTitle: 'Авторизация',
    biometrySubtitle: 'Подтвердите личность',
    loading: 'Загрузка...',
    serverUnavailable: 'Нет соединения с сервером',
};